from __future__ import annotations

import json
from typing import Any

from core.ai_clients.gpt_client import GptClient
from schemas.reference_bundle import FullSolutionBundle


AI_FALLBACK_WARNING = (
    "Answer generated by AI fallback from question text because no usable "
    "official answer was extracted. Teacher review required."
)


def _is_blank(value: Any) -> bool:
    return not str(value or "").strip()


def _part_identity(question_id: int, part: Any) -> str:
    label = str(getattr(part, "part", "") or getattr(part, "part_key", "") or "").strip()
    return f"Q{question_id}:{label}"


def find_missing_solution_parts(bundle: FullSolutionBundle | dict[str, Any]) -> list[dict[str, Any]]:
    """
    Return the full-solution parts that have question text but no usable answer.

    We require question_text so the fallback solves from the extracted question,
    not from a blank or ambiguous OCR fragment.
    """
    full = bundle if isinstance(bundle, FullSolutionBundle) else FullSolutionBundle.model_validate(bundle)

    missing: list[dict[str, Any]] = []
    for q in full.questions:
        for p in q.parts:
            has_question = not _is_blank(p.question_text) or not _is_blank(p.required_action)
            has_answer = not _is_blank(p.official_solution) or not _is_blank(p.expected_answer)
            if has_question and not has_answer:
                missing.append(
                    {
                        "question_id": int(q.question_id),
                        "part": p.part or "",
                        "part_key": p.part_key or p.part or "",
                        "question_text": p.question_text or "",
                        "required_action": p.required_action or "",
                    }
                )
    return missing


_FALLBACK_SCHEMA: dict[str, Any] = {
    "type": "object",
    "additionalProperties": False,
    "required": ["answers", "warnings"],
    "properties": {
        "answers": {
            "type": "array",
            "items": {
                "type": "object",
                "additionalProperties": False,
                "required": [
                    "question_id",
                    "part",
                    "part_key",
                    "official_solution",
                    "expected_answer",
                    "grading_instructions",
                    "confidence",
                    "warnings",
                ],
                "properties": {
                    "question_id": {"type": "integer"},
                    "part": {"type": "string"},
                    "part_key": {"type": "string"},
                    "official_solution": {"type": "string"},
                    "expected_answer": {"type": "string"},
                    "grading_instructions": {"type": "string"},
                    "confidence": {"type": "number"},
                    "warnings": {"type": "array", "items": {"type": "string"}},
                },
            },
        },
        "warnings": {"type": "array", "items": {"type": "string"}},
    },
}


_SYSTEM_PROMPT = """
You are MathGrade's solution-bank answer fallback.

Task:
- Fill ONLY missing answer/solution fields for math exam parts.
- Use the extracted question text and required action only.
- Do not claim the generated answer is the teacher's official answer.
- Preserve Hebrew wording where useful and preserve math in LaTeX.
- Return concise but complete solutions suitable for a teacher to review.
- If a part is too ambiguous to solve, return empty answer fields and add a warning.
- Do not modify question text.
- Return JSON only.
""".strip()


def _fallback_user_prompt(
    *,
    exam_id: str,
    source_name: str,
    missing_parts: list[dict[str, Any]],
    raw_ocr_text: str = "",
) -> str:
    raw_excerpt = (raw_ocr_text or "").strip()
    if len(raw_excerpt) > 12000:
        raw_excerpt = raw_excerpt[:12000] + "\n...[truncated]"

    return f"""
exam_id: {exam_id}
source_name: {source_name}

The following full-solution parts are missing usable extracted answers.
Generate draft answers for teacher review.

Missing parts JSON:
-------------------
{json.dumps(missing_parts, ensure_ascii=False, indent=2)}

Optional OCR context excerpt. Use only when it helps interpret symbols, but do not
copy hallucinated official answers from it unless visibly present:
-------------------
{raw_excerpt}
""".strip()


def fill_missing_answers_with_ai(
    *,
    full_solution_bundle: FullSolutionBundle | dict[str, Any],
    exam_id: str = "",
    source_name: str = "",
    client: Any = None,
    provider_label: str = "",
    model_label: str = "",
    raw_ocr_text: str = "",
) -> FullSolutionBundle:
    """
    Fill missing answer fields in a FullSolutionBundle using an AI fallback.

    Safety behavior:
      - never overwrites existing official_solution or expected_answer
      - marks generated parts as needs_review
      - records source_answer_file as ai_fallback:<provider>:<model>
    """
    full = (
        full_solution_bundle
        if isinstance(full_solution_bundle, FullSolutionBundle)
        else FullSolutionBundle.model_validate(full_solution_bundle)
    )

    missing = find_missing_solution_parts(full)
    if not missing:
        return full

    client = client or GptClient()

    result = client.chat_json(
        system=_SYSTEM_PROMPT,
        user=_fallback_user_prompt(
            exam_id=exam_id or full.exam_id,
            source_name=source_name,
            missing_parts=missing,
            raw_ocr_text=raw_ocr_text,
        ),
        schema=_FALLBACK_SCHEMA,
        schema_name="mathgrade_answer_fallback",
        strict=False,
        timeout_s=240,
    )

    generated_by_key: dict[str, dict[str, Any]] = {}
    for item in result.get("answers") or []:
        try:
            qid = int(item.get("question_id"))
        except Exception:
            continue
        label = str(item.get("part") or item.get("part_key") or "").strip()
        generated_by_key[f"Q{qid}:{label}"] = item

    filled_count = 0
    fallback_source = ":".join(
        x for x in ["ai_fallback", provider_label.strip(), model_label.strip()] if x
    ) or "ai_fallback"

    for q in full.questions:
        for p in q.parts:
            if not (_is_blank(p.official_solution) and _is_blank(p.expected_answer)):
                continue

            candidates = [
                _part_identity(q.question_id, p),
                f"Q{q.question_id}:{p.part_key or ''}",
                f"Q{q.question_id}:{p.part or ''}",
            ]
            generated = next((generated_by_key.get(k) for k in candidates if k in generated_by_key), None)
            if not generated:
                continue

            official_solution = str(generated.get("official_solution") or "").strip()
            expected_answer = str(generated.get("expected_answer") or "").strip()
            grading_instructions = str(generated.get("grading_instructions") or "").strip()

            if not official_solution and not expected_answer:
                warnings = [str(w) for w in (generated.get("warnings") or []) if str(w).strip()]
                p.review_status = "missing"
                p.warnings = list(dict.fromkeys([*(p.warnings or []), *warnings, AI_FALLBACK_WARNING]))
                continue

            p.official_solution = official_solution
            p.expected_answer = expected_answer
            p.grading_instructions = grading_instructions or p.grading_instructions
            p.review_status = "needs_review"
            p.confidence = generated.get("confidence") if generated.get("confidence") is not None else p.confidence
            p.source_answer_file = fallback_source

            generated_warnings = [str(w) for w in (generated.get("warnings") or []) if str(w).strip()]
            p.warnings = list(dict.fromkeys([*(p.warnings or []), AI_FALLBACK_WARNING, *generated_warnings]))
            filled_count += 1

    if filled_count:
        msg = f"AI fallback generated draft answers for {filled_count} missing solution part(s). Teacher review required."
        full.warnings = list(dict.fromkeys([*(full.warnings or []), msg, *[str(w) for w in (result.get("warnings") or [])]]))

    return full